name: Deploy web

on:
    push:
        branches: ["master"]

jobs:
    export_web:
        name: Export web
        type: build
        params:
            platform: web

    deploy_web:
        name: Deploy web
        needs: [export_web]
        type: deploy
        params:
            prod: true
